---

logging:
  level: INFO
  loggers:
    com.fsystem.apiresttask: DEBUG
mongoDB: test
mongoHost: mongo_host
mongoPort: 27017
mongoUser:
mongoPassword:
collectionName: tasks
server:
  applicationConnectors:
    -
      port: 8080
      type: http
