version: '3'
services:
  #************Mongo DB***************
  database_mongo:
    container_name: mongo_container
    image: mongo:latest
    hostname: mongo_host
    environment:
      - MONGO_INITDB_ROOT_DATABASE=database
    volumes:
      - ./mongodb_data_container:/data/db
      #means you want to set data on container persist on your local folder named mongo-volume . /data/database/ is a folder that already created inside the mongo container.
    ports:
      - 27017:27017
    networks:
      - todo_net
  #************Backend***************
  backend_dropwizard:
    container_name: dropwizard_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database_mongo
    networks:
      - todo_net

networks:
  todo_net:
    driver: bridge
